### ISSUE TITLE
URL設計

### ISSUE THREAD

**Issue by Ichiyo14** [Ichiyo14/my_memori#17]
[ペーパープロトタイプ](https://bootcamp.fjord.jp/products/10097)

<details><summary>初版</summary><div>

| Method|Path |Description | 
| :--- |:--- | :--- | 
|GET| /|トップページを取得する|
|GET|/sing_up|ログイン画面の表示|
|GET|/sing_in|サインイン画面の表示|
|GET| /questionnaires |質問一覧を表示する
|GET| /questionnaires/{questionnaires_id} | 詳細を見る|
|GET|/questionnaires/new| questionnairesの新規作成画面を表示する|
|POST |  /questionnaires  |/questionnairesに対して新しい子リソースを作成する   |
|GET|/questionnaires/{questionnaires_id}/answer| 回答入力画面を表示する
|POST | /questionnaires/{questionnaires_id}/answer    | 質問に回答する(answerに対して新しい子リソースを作成する)    |
|GET|/questionnaires/{questionnaires_id}/edit |  質問の編集画面を表示する
|PUT| /questionnaires/{questionnaires_id} | 質問を編集する|
|DELETE|/questionnaires/{/questionnaires_id} | 質問を削除する|

url上、``questionnaires``よりも``questions``の方が親しみがある単語のため``questions``を使った方がよいだろうか？

</div>
</details>

## 初版→修正版に当たる変更点
- ``questionnaire`` → ``question``へ
- 質問一覧の表示はユーザーが回答可能なものを表示させる
- 質問の詳細にはユーザーの回答情報を含め表示されることになるため、ユーザーIDと紐付けた
- 管理者（ユーザー）がユーザーに対し、質問を回答可能なものとして公開することがあるため、これに関するURLを追記

## 修正版
| Method|Path |Description | 
| :--- |:--- | :--- | 
|GET| /|トップページを取得する|
|GET|/sing_up|ログイン画面の表示|
|GET|/sing_in|サインイン画面の表示|
|GET| users/{user_id}/questions |ユーザーが回答可能な質問一覧を表示する |
|GET| users/{user_id}/questions/{question_id} | 質問の詳細画面を表示する|
|GET| /questions/new| questionsの新規作成画面を表示する|
|POST |  /questions  |/questionsに対して新しい子リソースを作成する   |
|GET| /questions/{question_id}/answer| 回答入力画面を表示する
|POST | /questions/{question_id}/answer | 質問に回答する(answerに対して新しい子リソースを作成する) |
|GET|/questions/{question_id}/edit |  質問の編集画面を表示する
|PUT| /questions/{question_id} | 質問を編集する|
|DELETE|/questions/{question_id} | 質問を削除する |
|POST| questions/{question_id}/users/{user_id}| 質問に対して、ユーザーに回答可能な情報を付与する|
|DELETE|questions/{question_id}/users/{user_id}|ユーザーが質問に対して持つ回答可能な情報を削除する|

**Comment by Ichiyo14** [comment]
| Method|Path |Description | 
| :--- |:--- | :--- | 
|GET| /|トップページを取得する|
|GET|/sing_up|ログイン画面の表示|
|GET|/sing_in|サインイン画面の表示|
|GET| /questionnaires |質問一覧を表示する
|GET| /questionnaires/{questionnaires_id} | 詳細を見る|
|GET|/questionnaires/new| questionnairesの新規作成画面を表示する|
|POST |  /questionnaires  |/questionnairesに対して新しい子リソースを作成する   |
|GET|/questionnaires/{questionnaires_id}/answer| 回答入力画面を表示する
|POST | /questionnaires/{questionnaires_id}/answer    | 質問に回答する(answerに対して新しい子リソースを作成する)    |
|GET|/questionnaires/{questionnaires_id}/edit |  質問の編集画面を表示する
|PUT| /questionnaires/{questionnaires_id} | 質問を編集する|
|DELETE|/questionnaires/{/questionnaires_id} | 質問を削除する|

url上、``questionnaires``よりも``questions``の方が親しみがある単語のため``questions``を使った方がよいだろうか？

[ペーパープロトタイプ](https://bootcamp.fjord.jp/products/10097)

**Comment by komagata** [comment]
> questionnaires

なるべく直訳でなく、questionとかsurveyとか他の短い簡潔な単語にしたほうがいいかも？と思いました〜。

**Comment by Ichiyo14** [comment]
@komagata 
``questionnaires`` →``question``へ変更しました！
他、違和感を感じた部分の修正をしました。お手数ですが、ご確認をお願いします🙏

**Comment by komagata** [comment]
@Ichiyo14 確認しました、OKですー🙆‍♂️

**Comment by Ichiyo14** [comment]
@komagata
ご確認ありがとうございます！
