### ISSUE TITLE
DB設計をする

### ISSUE THREAD

**Issue by Ichiyo14** [Ichiyo14/my_memori#7]
[ペーパープロトタイプ](https://bootcamp.fjord.jp/products/10097)

<details><summary>初版</summary><div>

<img width="666" alt="スクリーンショット 2021-12-02 19 56 13" src="https://user-images.githubusercontent.com/78020405/144409224-6af2d2f5-c9aa-4832-87a5-f9521b3aef42.png">

</div>
</details> 

## 2版

<img width="930" alt="スクリーンショット 2021-12-06 5 40 18" src="https://user-images.githubusercontent.com/78020405/144763213-e8b3776e-e609-4fde-9d62-5672a5b7ff53.png">

scaleをquestionnairesに持たせるか、questionsに持たせるか悩んでいます。google formなどの類似したアンケート作成アプリでは一つ一つ質問毎にscaleを付けている印象です。

## テーブル、カラムの詳細
- questionnaires:質問の大枠
- questions :個別の質問
- factor: 因子について
<img width="1340" alt="因子について" src="https://user-images.githubusercontent.com/78020405/144698940-38215ae8-4666-4a1f-81a0-49471c948946.png">

- scales:尺度について
<img width="1371" alt="尺度について" src="https://user-images.githubusercontent.com/78020405/144699103-6260b4eb-5582-49aa-9dfb-ef0aa8cc5d51.png">

- answers:質問への回答について

- answerable_questionnaires:ユーザーがどの質問に対して、回答することができるか？

### 質問新規作成の任意回答部分
<img width="1360" alt="任意回答のところ" src="https://user-images.githubusercontent.com/78020405/144763337-e2f881e1-5998-43b2-80a3-81392d6f55be.png">

**Comment by komagata** [comment]
FactorsやScalesが何に使われるのかちょっとわからなかったのですが、もう少し情報いただければありがたいです〜

**Comment by Ichiyo14** [comment]
@komagata 
Factors、Scalesに加え、情報を追記しました！
お手数ですが、ご確認をお願いします🙏

**Comment by komagata** [comment]
@Ichiyo14 確認しました、OKですー🙆‍♂️

**Comment by Ichiyo14** [comment]
@komagata 
ご確認ありがとうございます！
